name = "cloudflare-worker-typescript"
type = "webpack"
account_id = '0d2c0a5b601d717f2f9cd2da4cdcc3a1'
workers_dev = true
compatibility_date = "2024-12-01"
main = "./src/index.ts"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "REDIS_CONFIG"
id = "bbdcd21aee89499698ef06430b62c1ed"
preview_id = "bbdcd21aee89499698ef06430b62c1ed"

[vars]
SECRET_KEY = "your-secret-key"

[env.production]
vars = { UPSTASH_REDIS_REST_URL = "https://thankful-mako-22301.upstash.io", UPSTASH_REDIS_TOKEN = "AVcdAAIjcDE2NGE4ODg1OGQ5MzI0NDg1YmQwYTU3OGRjNDZhOTVhMnAxMA"}

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
