name = "cloudflare-worker-typescript"
type = "javascript"
route = ''
zone_id = ''
account_id = '0d2c0a5b601d717f2f9cd2da4cdcc3a1'
compatibility_flags = []
workers_dev = true
compatibility_date = "2024-11-30"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"